# Configuración de Netlify para el proyecto de Horarios

[build]
  # Comando de build (no necesario para este proyecto estático)
  command = "echo 'No build required'"
  
  # Directorio de publicación
  publish = "."

[build.environment]
  # Variables de entorno para Firebase (configurar en Netlify Dashboard)
  FIREBASE_API_KEY = ""
  FIREBASE_AUTH_DOMAIN = ""
  FIREBASE_PROJECT_ID = ""
  FIREBASE_STORAGE_BUCKET = ""
  FIREBASE_MESSAGING_SENDER_ID = ""
  FIREBASE_APP_ID = ""

# Configuración de headers para mejorar seguridad
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Headers específicos para archivos JavaScript
[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Headers para archivos CSS
[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Redirecciones (opcional)
[[redirects]]
  from = "/horario"
  to = "/"
  status = 301